lib/util/objects/flying_attack_angle_object.dart, lib/util/objects/flying_attack_object.dart
Do jeito que está implementado hoje, na esquerda e topo o attack é removido ao sair da tela, enquanto pra direita e baixo ele ultrapassa o limite do mapa...
=> fix verify exists in world

CHANGELOG.md, example/lib/player/knight.dart, example/pubspec.lock, lib/util/talk/say.dart, lib/util/talk/talk_dialog.dart
Hey!
This PR introduces the possibility to use `TextSpan` in `TalkDialog`, being useful to give a highlight in certain words.
It is a **breaking change** because I think it is better to ask directly for the `List<TextSpan>` instead of multiple strings and textStyles.
It also adds the  `speed` param to control how long it takes to show each character.
Let me know what you think.
As always, thank you @RafaelBarbosatec !
Preview:
=> Refactor TalkDialog core to allow RichText animations

example/lib/player/knight.dart, lib/player/player.dart, lib/player/rotation_player.dart, lib/util/extensions/extensions.dart, lib/util/extensions/joystick_extensions.dart, lib/util/mixins/movement_by_joystick.dart
**Firstly**
It started by trying to fix `RotationPlayer` as it was translating it's position twice in the `update` method on `moveFromAngle` and `super.update` which updated position again in `MovementByJoystick` mixin.
So by removing the movement from `RotationPlayer` and moving it to `MovementByJoystick` I was able to make it update the position only once.
**Secondly**
Now both `RotationPlayer` and `SimplePlayer` (and any `Player` for that matter) should be able to move in either 360 degree mode or stay in the default locked 8-way mode. This will work on PC keyboard with directional arrows or with on screen joystick.
joystick_extensions.dart line 13 is not great, but I'm not sure how to better handle this
=> improve player joystick movement

CHANGELOG.md, example/lib/shared/player/knight.dart, example/lib/tiled_map/game_tiled_map.dart, example/pubspec.lock, lib/joystick/joystick.dart, lib/util/talk/talk_dialog.dart
**Suggestion**: We can start merging PRs with the squash option (selectable in the merge button dropdown) so every commit in the PR is grouped into a single commit, just like the Flame team does in their project.
This PR:
- Changes `logicalKeyboardKeyToNext` in `TalkDialog` to `logicalKeyboardKeysToNext` and now takes a List of keys to advance dialogue (Breaking Change, now it requires a `List<LogicalKeyboardKey>?` instead of `LogicalKeyboardKey?`);
-  Adds the option `wasdAndArrows` to `KeyboardDirectionalType` allowing both arrows and wasd keys to control the joystick.
Does your PR require Flame users to manually …
=> Improvements in Joystick

CHANGELOG.md, example/assets/images/tiled/mapa1.json, example/lib/shared/enemy/goblin.dart, example/pubspec.lock, lib/camera/camera.dart, lib/tiled/tiled_world_map.dart, lib/util/collision_game_component.dart, lib/util/extensions/enemy/enemy_extensions.dart, lib/util/text_game_component.dart, pubspec.lock, pubspec.yaml
- Adds support to add objects with collision by Tiled. Just add the object and set you type to `collision`. [#210](https://github.com/RafaelBarbosatec/bonfire/issues/210)
- Improvements in `worldPositionToScreen`. Now considers zoom.
- Improvements in `seeAndMoveToPlayer` and `seeAndMoveToAttackRange`. Adds `notObserved` and `observed`.
=> Version 1.12.2

CHANGELOG.md, example/lib/shared/decoration/spikes.dart, example/lib/shared/enemy/goblin.dart, example/lib/tiled_map/game_tiled_map.dart, example/pubspec.lock, lib/base/game_component.dart, lib/bonfire.dart, lib/camera/bonfire_camera.dart, lib/collision/collision_area.dart, lib/collision/collision_config.dart, lib/collision/object_collision.dart, lib/joystick/joystick_move_to_position.dart, lib/util/direction_animations/simple_direction_animation.dart, lib/util/extensions/extensions.dart, lib/util/extensions/game_component_extensions.dart, lib/util/mixins/interval_checker.dart, lib/util/mixins/move_to_position_along_the_path.dart, lib/util/mixins/sensor.dart, lib/util/mixins/tile_recognizer.dart, pubspec.yaml
- Improvement in `JoystickMoveToPosition`. New:
- adds `enabledMoveCameraWithClick` param to enable movements of the camera with click and move movements.
- adds `mouseButtonUsedToMoveCamera` param to set what button of the mouse you can use to move the camera.
- adds `mouseButtonUsedToMoveToPosition` param to set what button of the mouse you can use to set the position target. Default is `secondary` (right mouse button).
- Extracted functions about check `Tiles` to the mixin `TileRecognizer`.
=> Version 2.4.3

CHANGELOG.md, lib/camera/bonfire_camera.dart, lib/map/map_world.dart
When the BonfireCamera changes his zoom, the moveOnlyMapArea property wasn't updating his limits. I've fixed that in this PR.
When the camera zoom changes, the limits are updated too.
Previously, the way it was being done, this should be updated when the map size changes, but the map size never changes, only the zoom. I changed the logic of the function that does this to be based on changing the zoom, rather than changing the size of the map.
This closes the issue [#267](https://github.com/RafaelBarbosatec/bonfire/issues/267).
=> fix(map): :bug: Update moveOnlyMapArea limits after changing camera zoom

CHANGELOG.md, lib/base/game_component.dart
Someone was confused why there code wasn't working on the discord and it was due to that they had forgotten to call `super.update`, this should make their IDE's warn them when they don't.
=> fix: Add mustCallSuper to GameComponent.update and onRemove

CHANGELOG.md, lib/tiled/builder/tiled_world_builder.dart
Fix the issue described in [417](https://github.com/RafaelBarbosatec/bonfire/issues/417) about collision computation in tileset when we use individual tiles definition
=> Fix collision & animation computation when a tileset use individual tiles definitions

CHANGELOG.md, example/lib/shared/decoration/potion_life.dart, lib/base/bonfire_game.dart, lib/base/bonfire_game_interface.dart, lib/bonfire.dart, lib/mixins/move_per_cell.dart, lib/mixins/vision.dart, lib/objects/flying_attack_game_object.dart, lib/util/extensions/game_component_extensions.dart, lib/util/text_damage_component.dart, pubspec.yaml
- Create mixin `MovePerCell`.
- Create mixin `CanNotSeen`. Use it to turn your component not detectable from `Vision` mixin.
- Update `showDamage` method.`initVelocityUp` renamed to `initVelocityVertical` and adds param `initVelocityHorizontal`.
- Fix issue [#455](https://github.com/RafaelBarbosatec/bonfire/issues/455)
- Fix bug [#474](https://github.com/RafaelBarbosatec/bonfire/issues/474)
=> Version 3.0.10

CHANGELOG.md, example/lib/pages/mini_games/simple_example/my_enemy.dart, lib/collision/block_movement_collision.dart, lib/mixins/automatic_random_movement.dart, lib/mixins/movement.dart, lib/util/extensions/game_component_extensions.dart, pubspec.yaml
- fix bug `AutomaticRandomMovement`. (not stop movement in collision)
- fix bug `BlockMovementCollision`.(pushing other)
- fix bug `simpleAttackMeleeByDirection`.(pushing enemy to inside other collision)
=> Version 3.1.2

CHANGELOG.md, example/lib/pages/input/keyboard/barrel_show_keyboard_input.dart, example/lib/pages/parallax/bonfire/bonfire_parallax_background.dart, example/lib/pages/parallax/flame/parallax_background.dart, example/pubspec.lock, lib/base/base_game.dart, lib/base/bonfire_game.dart, lib/base/bonfire_game_interface.dart, lib/base/listener_game_widget.dart, lib/color_filter/color_filter_component.dart, lib/game_interface/game_interface.dart, lib/input/keyboard/control_by_keyboard.dart, lib/input/keyboard/keyboard_listener.dart, lib/input/player_controller.dart, lib/lighting/lighting_component.dart, lib/util/priority_layer.dart, lib/util/talk/talk_dialog.dart, lib/widgets/bonfire_widget.dart, pubspec.lock, pubspec.yaml
- Adds param `hudComponents` in `BonfireWidget`.
- Adds `queryHud` method in `BonfireGameInterface`
- Adds `addHud` method in `BonfireGameInterface`
- Update Flame to `1.16.0`
=> Version 3.6.0

CHANGELOG.md, lib/background/background_image_game.dart, lib/base/game_component.dart, lib/bonfire.dart, lib/map/empty_map.dart, lib/map/world_map.dart, lib/mixins/flip_render.dart, lib/tiled/map_world_by_tiled.dart, pubspec.yaml
- standardizes 'onLoad' method.
- adds 'size' in 'EmptyWorldMap'.
- adds mixin 'FlipRender'.
=> Version 3.6.2

lib/widgets/bonfire_widget.dart
Make keyboard work for my own sanity
*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If this is a breaking change, specify explicitly which APIs have been changed*
=> Keyboard not used on build

CHANGELOG.md, example/lib/pages/mini_games/tiled_map/game_tiled_map.dart, lib/input/keyboard/control_by_keyboard.dart, lib/input/keyboard/keyboard_config.dart, lib/npc/enemy/platform_enemy.dart, lib/util/extensions/extensions.dart, lib/util/extensions/image_extensions.dart, pubspec.yaml
- `KeyboardConfig` improvements. Now `directionalKeys` expect list of `KeyboardDirectionalKeys`. Fix [#507](https://github.com/RafaelBarbosatec/bonfire/issues/507)
- `PlatformEnemy` improvements.
- Adds `flipAnimation` method in `ui.Image`.
=> Version 3.8.4

CHANGELOG.md, lib/collision/block_movement_collision.dart, lib/mixins/direction_animation.dart
1. Fix for #520 
2. Refactoring some code - like moving `super.onCollision` calls to the end of the method.
=> Fix for #520

CHANGELOG.md, lib/objects/flying_attack_game_object.dart
- Add guard in `FlyingAttackGameObject` to prevent calling `onDestroy` after component has been destroyed.
- Refactor: remove redundant parameters
=> Add guard to prevent `onDestroy` being called after component has been removed

CHANGELOG.md, lib/mixins/jumper.dart
- Character displays run animation instead of jump animation on slanting tiles
To elaborate on what this PR does:
Before the change:
https://github.com/RafaelBarbosatec/bonfire/assets/7362366/fb334cdb-9b05-49c9-80ea-ce955ff2bd20
After the change:
https://github.com/RafaelBarbosatec/bonfire/assets/7362366/ed80be47-951a-47f0-871e-28b8e4222320
=> Fix bug where character goes into jump mode on slanting floors

CHANGELOG.md, example/lib/pages/player/simple/human.dart, example/lib/shared/decoration/spikes.dart, lib/collision/block_movement_collision.dart, lib/collision/collision_util.dart, lib/mixins/attackable.dart, lib/objects/flying_attack_game_object.dart, lib/util/damage_hitbox.dart, pubspec.yaml
- Fix bug when hitbox anchor is center.
- BREAKING CHANGE: Update `bool receiveDamage` to `void onReceiveDamage`. Now to perform receive of attack use `handleAttack` method.
=> Version 3.9.8

CHANGELOG.md, lib/map/matrix_map/matrix_layer.dart
`MatrixLayer` class had a bug making it impossible to set `axisInverted` field. The PR makes the `axisInverted` set by the constructor.
- [x ] No, this is *not* a breaking change.
=> Fix: MatrixLayer axisInverted field

CHANGELOG.md, example/pubspec.lock, pubspec.lock, pubspec.yaml
Fixed #547 
```console
/xxx/Pub/Cache/hosted/pub.dev/flame-1.17.0/lib/src/game/notifying_vector2.dart:189:30: Error: The method 'UnmodifiableFloat64ListView' isn't defined for the class 'NotifyingVector2'. - 'NotifyingVector2' is from 'package:flame/src/game/notifying_vector2.dart' ('/xxx/Pub/Cache/hosted/pub.dev/flame-1.17.0/lib/src/game/notifying_vector2.dart').
Try correcting the name to the name of an existing method, or defining a method named 'UnmodifiableFloat64ListView'.
Float64List get storage => UnmodifiableFloat64ListView(super.storage);
```
- BREAKING CHANGE: Bump Flutter SDK minimum version to 3.22.0
- Upgrade: Packages (flame v1.18.0, http v1.2.2, a_star_algorithm v0.3.2).
Before you create this PR confirm that it meets all requirements listed below by checking the relevant …
=> Fix: Doesn't work (Flutter v3.24.0)

CHANGELOG.md, example/lib/pages/enemy/melee_enemy.dart, lib/mixins/random_movement.dart, pubspec.yaml
- `RandomMovement` improvements
=> Version 3.12.2

.github/workflows/publish.yml, CHANGELOG.md, lib/mixins/random_movement.dart, pubspec.yaml
- `RandomMovement` improvements
=> Version 3.12.3
