RafaelBarbosatec/bonfire

README.md, README_PT.md
Hey! In this PR I tried to explain better some parts of the docs and fixed some typos, I hope it is useful :) @RafaelBarbosatec
=> [PT-BR] [Docs] Fix some typos

README.md
=> Traslate the hell up on that README

CHANGELOG.md, README.md, README_PT.md, example/lib/game_manual_map.dart, example/lib/game_tiled_map.dart, example/lib/player/knight.dart, example/pubspec.lock, lib/bonfire_tiled_widget.dart, lib/bonfire_widget.dart, lib/map/map_world.dart, lib/rpg_game.dart, lib/util/base_game_point_detector.dart, lib/util/camera.dart, lib/util/lighting/lighting.dart, pubspec.yaml
[0.6.4]
* add Zoom camera by [rezendegc](https://github.com/rezendegc).
* improvements TiledObjects.
* improvements Joystick.
=> Version 0.6.4

CHANGELOG.md, lib/joystick/joystick_action.dart, lib/joystick/joystick_directional.dart, lib/tiled/tiled_world_map.dart, pubspec.yaml
* Optimizations when loading maps built with Tiled
=> version 0.6.5

lib/joystick/joystick_action.dart
I converted the action id from int to dynamic for better id maintenance, such as strings, enums, etc
=> converted action id from int to dynamic for better id management

lib/objects/flying_attack_object.dart
Diagonals were not moving correctly.
This should fix it
=> fix position translation on diagonal movement of FlyingAttackObject

CHANGELOG.md, example/pubspec.lock, lib/base/bonfire_game.dart, lib/camera/camera.dart, lib/map/map_game.dart, lib/map/map_world.dart, lib/map/tile/tile.dart, lib/map/tile/tile_model.dart, lib/objects/flying_attack_object.dart, pubspec.lock, pubspec.yaml
- improvements in `MapWorld`
- enables remove tiles of map.
- fix position translation on diagonal movement of FlyingAttackObject [#155](https://github.com/RafaelBarbosatec/bonfire/pull/155)
=> Version 1.4.11

CHANGELOG.md, example/lib/enemy/goblin.dart, example/pubspec.lock, lib/base/bonfire_game.dart, lib/base/custom_base_game.dart, lib/camera/camera.dart, lib/map/map_world.dart, lib/util/extensions/extensions.dart, lib/util/map_explorer.dart, lib/util/quadtree.dart, pubspec.lock, pubspec.yaml
Add a little adaptation of the [quadTree](https://github.com/TheAlgorithms/Dart/blob/master/data_structures/quad_tree/quad_tree.dart) data struct to search visible tiles.
=> Add QuadTree

CHANGELOG.md, lib/base/bonfire_game.dart, lib/base/game_component.dart, lib/objects/flying_attack_object.dart, lib/util/extensions/enemy/enemy_extensions.dart, lib/util/extensions/game_component_extensions.dart, lib/util/extensions/player/player_extensions.dart, lib/util/mixins/pointer_detector.dart, lib/widgets/bonfire_tiled_widget.dart, lib/widgets/bonfire_widget.dart, pubspec.yaml
- adds `getScreenPosition` method in `GameComponent`.
- adds `enableDiagonal` param in `simpleAttackRange`.
- adds `visibleComponentsByType` and `componentsByType` in `BonfireGame`.
- adds `onTapDown` and `onTapUp` in `BonfireTiledWidget` and `BonfireWidget`.
=> Version 1.6.0

CHANGELOG.md, example/lib/game_tiled_map.dart, example/lib/interface/knight_interface.dart, example/pubspec.lock, lib/base/game_component.dart, lib/bonfire.dart, lib/util/follower_widget.dart, lib/util/mixins/move_to_position_along_the_path.dart, pubspec.lock, pubspec.yaml
- adds `FollowerWidget`. With this you can add a widget what follows a component in the game.
- update `a_star_algorithm`. now enables diagonal movements.
=> Version 1.7.0

.github/pull_request_template.md, CHANGELOG.md, lib/joystick/joystick.dart, pubspec.yaml
- Bugfix/quadtree id for removal [#178](https://github.com/RafaelBarbosatec/bonfire/pull/178)
- Adds `keyboardDirectionalType` param in `Joystick` to enable WASD.
=> Version 1.8.0

CHANGELOG.md, example/lib/shared/enemy/goblin.dart, lib/util/extensions/enemy/enemy_extensions.dart, lib/util/mixins/move_to_position_along_the_path.dart, pubspec.yaml
- Update params name of `simpleAttackMelee` in Enemy.
- Improvements in `MoveToPositionAlongThePath`
=> Version  1.9.5

CHANGELOG.md, example/lib/shared/player/knight.dart, example/lib/tiled_map/game_tiled_map.dart, example/pubspec.lock, lib/joystick/joystick.dart, lib/util/mixins/move_to_position_along_the_path.dart, lib/util/talk/talk_dialog.dart, pubspec.yaml
- Fix bug "getting stuck" in `MoveToPositionAlongThePath`
- [BREAKING CHANGE] Change param `logicalKeyboardKeyToNext` in `TalkDialog` to `logicalKeyboardKeysToNext`, now multiple keys are accepted to advance in the dialogue
- Add option `wasdAndArrows` to `KeyboardDirectionalType` allowing both arrows and wasd keys to control the joystick
- Improvements in diagonal movements in `MoveToPositionAlongThePath`
=> Version 1.9.6

CHANGELOG.md, lib/base/bonfire_game.dart, lib/camera/camera.dart, lib/camera/camera_config.dart
Added an `angle` property to the `Camera`. This allows us to rotate the camera. Also added appropriate animate methods for it
=> add angle to the camera so we can rotate the whole view

CHANGELOG.md, example/lib/manual_map/game_manual_map.dart, example/lib/shared/player/knight.dart, lib/camera/camera.dart, lib/util/game_controller.dart, lib/util/mixins/move_to_position_along_the_path.dart, lib/util/talk/talk_dialog.dart, pubspec.yaml
- Improvements in `TalkDialog.show` : add `onClose`.
- Add rotation functionality to the camera. Set `angle` on `CameraConfig` or `animateRotate` to rotate the camera view
=> Version 1.9.7

CHANGELOG.md, lib/map/map_assets_manager.dart, lib/util/mixins/move_to_position_along_the_path.dart, pubspec.yaml
- Fix rounding of movement in `MoveToPositionAlongThePath`.
- Fix loaded map by url.
=> Version 1.9.8

CHANGELOG.md, example/lib/shared/interface/knight_interface.dart, lib/camera/camera.dart, lib/util/talk/talk_dialog.dart
Added a new rotation method in Camera and dismissible option in TalkDialog.
=> Add animateLoopRotation method in Camera

CHANGELOG.md, example/lib/shared/interface/knight_interface.dart, lib/base/base_game.dart, lib/base/bonfire_game.dart, lib/camera/camera.dart, lib/map/map_assets_manager.dart, lib/util/talk/talk_dialog.dart, pubspec.yaml
- Add `dismissible` param in `TalkDialog.show` to avoid the dialogue being dismissed when the back button is pressed or esc key is pressed on desktop.
- Add `animateLoopRotation` method in camera.
- Rename `animateRotate` to `animateSimpleRotation`.
- Improvements in rotation effect.
=> Version 1.9.9

CHANGELOG.md, example/pubspec.lock, lib/tiled/tiled_world_map.dart, pubspec.yaml
- Fix problem render big tilesets [#200](https://github.com/RafaelBarbosatec/bonfire/issues/200).
=> Version 1.9.10

CHANGELOG.md, example/lib/shared/enemy/goblin.dart, example/lib/shared/enemy/goblin_rotation.dart, example/lib/shared/player/knight.dart, lib/background/background_image_game.dart, lib/collision/object_collision.dart, lib/map/map_assets_manager.dart, lib/map/tile/tile_model.dart, lib/util/extensions/enemy/enemy_extensions.dart, lib/util/extensions/enemy/rotation_enemy_extensions.dart, lib/util/extensions/game_component_extensions.dart, lib/util/extensions/player/player_extensions.dart, lib/util/extensions/player/rotation_player_extensions.dart, lib/util/talk/talk_dialog.dart, pubspec.yaml
- improvements in sprite load of the `BackgroundImageGame`.
- improvements in `simpleAttackRangeByAngle`.
- rename `animationTop` to `animationUp`
- rename `animationBottom` to `animationDown`
- improvements in `TalkDialog`
=> Version 1.12.1

CHANGELOG.md, example/assets/images/tiled/mapa1.json, example/assets/images/tiled/tileset/0x72_DungeonTilesetII_v1.json, example/pubspec.lock, lib/collision/collision_area.dart, lib/tiled/tiled_world_map.dart, lib/util/collision_game_component.dart, pubspec.yaml
- Improvements in collision objects by Tiled.
=> Version 1.12.3

CHANGELOG.md, example/pubspec.lock, lib/tiled/model/tiled_object_properties.dart, lib/tiled/tiled_world_map.dart, pubspec.yaml
- Add params `name` and `id` in `TiledObjectProperties`.
=> Version 1.12.5

CHANGELOG.md, example/lib/top_down_game/soldier_player.dart, example/pubspec.lock, lib/base/game_component.dart, lib/enemy/rotation_enemy.dart, lib/objects/flying_attack_object.dart, lib/util/bonfire_game_ref.dart, lib/util/direction_animations/simple_direction_animation.dart, lib/util/extensions/enemy/rotation_enemy_extensions.dart, lib/util/mixins/automatic_random_movement.dart, lib/util/mixins/direction_animation.dart, lib/util/mixins/move_to_position_along_the_path.dart, lib/util/mixins/movement.dart, lib/util/mixins/movement_by_joystick.dart, pubspec.yaml
- Improvements in `DirectionAnimation` mixin.
- Improvements in `Movement` mixin. Adds `onMove` method, you can override this to listen component movements
=> Version 2.2.2

CHANGELOG.md, example/lib/shared/player/knight.dart, lib/background/background_image_game.dart, lib/base/game_component.dart, lib/player/rotation_player.dart, lib/tiled/tiled_world_map.dart, lib/util/mixins/movement_by_joystick.dart, lib/util/talk/talk_dialog.dart, pubspec.yaml
- Improvements in `MovementByJoystick`.
- Improvements in access to gameRef in `GameComponent`.
- Improvements in `ImageLayer`.
- Fix bug in `TalkDialog`. issue [#224](https://github.com/RafaelBarbosatec/bonfire/issues/224).
=> Version 2.2.4

CHANGELOG.md, example/lib/shared/decoration/barrel_dragable.dart, example/lib/shared/player/knight.dart, lib/map/map_world.dart, lib/objects/flying_attack_object.dart, pubspec.yaml
- Fix crash mentioned in the issue [#255](https://github.com/RafaelBarbosatec/bonfire/issues/225)
- Fix crash mentioned in the issue [#227](https://github.com/RafaelBarbosatec/bonfire/issues/227)
=> Version 2.2.5

CHANGELOG.md, example/lib/shared/enemy/goblin_controller.dart, example/lib/shared/interface/bar_life_controller.dart, example/lib/shared/npc/critter/critter_controller.dart, example/lib/shared/player/knight_controller.dart, example/pubspec.lock, lib/base/custom_game_widget.dart, lib/camera/bonfire_camera.dart, lib/state_manager/state_controller.dart, lib/state_manager/use_state_controller.dart, lib/widgets/bonfire_tiled_widget.dart, lib/widgets/bonfire_widget.dart, pubspec.yaml
- Adds params `focusNode`, `autofocus` and `mouseCursor` in `BonfireWidget` and `BonfireTiledWidget`. RafaelBarbosatec/bonfire/issues/250
- Improvements in `Camera`
- BREAKING CHANGE: Update `StateController`. the method `update` now is `void update(double dt, T component)`. Now you receive what component belongs this update in case that your controller is used in many components.
=> Version 2.4.2

CHANGELOG.md, example/lib/main.dart, example/lib/random_map/player/pirate.dart, example/lib/shared/interface/knight_interface.dart, example/pubspec.lock, lib/base/base_game.dart, lib/base/bonfire_game.dart, lib/base/bonfire_game_interface.dart, lib/camera/bonfire_camera.dart, lib/game_interface/game_interface.dart, lib/map/map_game.dart, lib/map/map_world.dart, lib/objects/animated_object_once.dart, lib/objects/flying_attack_object.dart, lib/state_manager/use_state_controller.dart, lib/util/extensions/extensions.dart, lib/util/extensions/game_component_extensions.dart, lib/util/mixins/movement.dart, lib/util/overlay_manager.dart, lib/util/text_damage_component.dart, lib/widgets/bonfire_tiled_widget.dart, lib/widgets/bonfire_widget.dart, pubspec.lock, pubspec.yaml
- Update `flame` to `1.2.0` - [CHANGELOG](https://pub.dev/packages/flame/changelog)
- Renamed `gameRef.overlays` to `gameRef.overlayManager`
- Renamed `GameComponent.shouldRemove` to `GameComponent.isRemoving`
- Remove `showFPS` in `BonfireTiledWidget` and `BonfireWidget`.
- Fix Camera bug in a small map that is not the size of the screen. [#261](https://github.com/RafaelBarbosatec/bonfire/issues/261)
=> Version 2.6.0

CHANGELOG.md, example/lib/shared/decoration/potion_life.dart, example/pubspec.lock, example/pubspec.yaml, lib/base/bonfire_game.dart, lib/base/bonfire_game_interface.dart, lib/bonfire.dart, lib/camera/bonfire_camera.dart, lib/color_filter/color_filter_component.dart, lib/lighting/lighting_component.dart, lib/tiled/tiled_world_map.dart, lib/util/effects/opacity_effect.dart, lib/util/extensions/extensions.dart, lib/util/extensions/game_component_extensions.dart, lib/util/value_generator_component.dart, pubspec.lock, pubspec.yaml
- removed `getValueGenerator` from `BonfireGame`. Now use `generateValues` from your component.
- removed `addParticle` from `BonfireGame`. Now use `addParticle` from your component.
- improvements in `ValueGeneratorComponent`
- Adds support to new files of the Tiled 1.8.0 (`tmj`,'tsj') . Fix issue [#263](https://github.com/RafaelBarbosatec/bonfire/issues/263)
- Adds effect `BonfireOpacityEffect`.
=> Version  2.6.1

CHANGELOG.md, example/lib/lpc/lpc_game.dart, example/lib/lpc/lpc_player.dart, example/pubspec.lock, lib/base/bonfire_game.dart, lib/base/game_component.dart, lib/joystick/joystick.dart, lib/state_manager/use_state_controller.dart, lib/widgets/bonfire_tiled_widget.dart, pubspec.yaml
- Fix: update map limits using `moveOnlyMapArea` after camera zoom changes. [#267](https://github.com/RafaelBarbosatec/bonfire/issues/267)
- Adds `Future updateDirectional(JoystickDirectional? directional)` in `Joystick`. [#269](https://github.com/RafaelBarbosatec/bonfire/issues/269)
=> Version 2.6.3

lib/util/talk/talk_dialog.dart
add talkAlignment in the talk box (optional), for default is Alignment.bottomCenter 
=> add talkAlignment in the talk box

CHANGELOG.md, lib/objects/animated_object_once.dart, lib/objects/flying_attack_object.dart, lib/util/direction_animations/simple_direction_animation.dart, lib/util/mixins/use_sprite_animation.dart, lib/util/talk/talk_dialog.dart, pubspec.yaml
- adds `playSpriteAnimationOnce` in mixin `UseSpriteAnimation`
- Fix destroy position in `FlyingAttackObject`
=> Version 2.7.2

CHANGELOG.md, example/lib/shared/decoration/chest.dart, example/lib/shared/player/knight.dart, lib/base/listener_game_widget.dart, lib/objects/animated_follower_object.dart, lib/util/extensions/enemy/rotation_enemy_extensions.dart, lib/util/extensions/game_component_extensions.dart, lib/util/extensions/player/rotation_player_extensions.dart, lib/util/mixins/follower.dart, pubspec.yaml
- Improvements in `Follower`.
- Improvements in `simpleAttackRangeByAngle` and `simpleAttackMeleeByAngle`
=> Version 2.7.3

CHANGELOG.md, example/lib/top_down_game/robot_enemy.dart, example/lib/top_down_game/soldier_player.dart, lib/bonfire.dart, lib/gestures/mouse_gesture.dart, lib/joystick/joystick_move_to_position.dart, lib/util/extensions/enemy/rotation_enemy_extensions.dart, lib/util/extensions/extensions.dart, lib/util/extensions/game_component_extensions.dart, lib/util/extensions/movement_extensions.dart, lib/util/extensions/npc/npc_extensions.dart, lib/util/functions.dart, lib/util/mixins/automatic_random_movement.dart, lib/util/mixins/interval_checker.dart, lib/util/mixins/movement.dart, lib/util/mixins/vision.dart, lib/util/util.dart, pubspec.yaml
- Improvements in `MouseGesture`.
- Improvements in `RotationEnemyExtensions`.
- Adds `BonfireUtil`.
- Adds optional param `firstCheckIsTrue` in `checkInterval` method.
- Adds param `useAngle` in `runRandomMovement` method (`AutomaticRandomMovement`). To use in components top-dow.
- Update top-down example.
=> Version 2.7.5

CHANGELOG.md, example/lib/shared/decoration/potion_life.dart, example/lib/shared/decoration/spikes.dart, example/pubspec.lock, lib/util/mixins/sensor.dart, pubspec.yaml
- Adds `onContactExit` in `Sensor` mixin.
=> Version 2.8.0

CHANGELOG.md, lib/map/world_map.dart, lib/util/extensions/movement_extensions.dart, lib/util/extensions/npc/npc_extensions.dart, lib/util/mixins/move_to_position_along_the_path.dart, pubspec.yaml
- improvements in `MoveToPositionAlongThePath`. Resolve issue [299](https://github.com/RafaelBarbosatec/bonfire/issues/299)
- improvements in `followComponent`. Now return `true` if can move. Resolve issue [301](https://github.com/RafaelBarbosatec/bonfire/issues/301)
=> Version 2.9.1

CHANGELOG.md, lib/util/extensions/movement_extensions.dart, lib/util/extensions/npc/npc_extensions.dart, pubspec.yaml
- Improvements in `seeAndMoveToPlayer`. Adds param `notCanMove` suggested by issue [303](https://github.com/RafaelBarbosatec/bonfire/issues/303)
- Improvements in `positionsItselfAndKeepDistance`.
=> Version 2.9.2

CHANGELOG.md, lib/util/direction_animations/simple_direction_animation.dart, lib/util/mixins/automatic_random_movement.dart, lib/util/mixins/direction_animation.dart, lib/util/mixins/move_to_position_along_the_path.dart, lib/util/mixins/sensor.dart, lib/util/mixins/use_sprite_animation.dart, pubspec.yaml
- Adds `pauseAnimation` and `resumeAnimation` in `UseSpriteAnimation` mixin.
- Adds `pause` and `resume` in `SimpleDirectionAnimation`
- Improvements in `MoveToPositionAlongThePath`. Adds `factorInflateFindArea` in `setupMoveToPositionAlongThePath` method.
- Improvements in `DirectionAnimation`.
=> Version 2.9.3

lib/tiled/builder/tiled_world_builder.dart
No changes to behavior (removed one duplicate and nested ` if (data.animation != null) {`)  along with dart style.
Was digging through this part of the code wanting to understand the difference between it and flame_tiled.  Looking at a change there for isometric.
- [?] I have added a description of the change under `[next]` in `CHANGELOG.md`.
* there is no "[next]" in changelog.md
=> Mostly dart cleanup while looking at tiled code

CHANGELOG.md, example/lib/shared/decoration/potion_life.dart, lib/camera/bonfire_camera.dart, lib/map/base/map_game.dart, lib/map/base/tile.dart, lib/map/world_map.dart, lib/objects/flying_attack_object.dart, lib/util/extensions/game_component_extensions.dart, lib/util/mixins/attackable.dart, lib/util/mixins/move_to_position_along_the_path.dart, lib/util/mixins/sensor.dart, pubspec.yaml
- Adds `revive` method in `Attackable` mixin. Now if adds life to stay above 0 it's is revive.
- Adds `onFinish` in `moveToPositionAlongThePath` method. (`MoveToPositionAlongThePath` mixin)
- Improvements in `WorldMap`
- Mostly dart cleanup while looking at tiled code. Thanks [jtmcdole](https://github.com/jtmcdole)!
=> Version 2.9.4

CHANGELOG.md, example/lib/shared/decoration/barrel_dragable.dart, example/lib/tiled_map/game_tiled_map.dart, lib/base/bonfire_game.dart, lib/collision/object_collision.dart, lib/lighting/lighting_component.dart, lib/map/base/tile.dart, lib/map/world_map.dart, lib/mixins/automatic_random_movement.dart, lib/mixins/direction_animation.dart, lib/mixins/paint_transformer.dart, lib/mixins/sensor.dart, lib/util/direction_animations/simple_direction_animation.dart, pubspec.yaml
- performance improvements
- Improvements in `SimpleDirectionAnimation`. Now you can use diagonal animation passing only right animation: `runUpRight`,`runDownRight`,`idleUpRight`,`idleDownRight`. Resolve issue [316](https://github.com/RafaelBarbosatec/bonfire/issues/316)
=> Version 2.10.3

CHANGELOG.md, lib/mixins/automatic_random_movement.dart, lib/mixins/direction_animation.dart, lib/mixins/follower.dart, lib/mixins/vision.dart, pubspec.yaml
- Improvements in `AutomaticRandomMovement`
- Improvements in `Follower`
=> Version 2.10.5

CHANGELOG.md, example/lib/shared/interface/knight_interface.dart, lib/mixins/automatic_random_movement.dart, pubspec.yaml
Fix bug tendency to go to the right in `AutomaticRandomMovement`.
=> Version 2.10.7

CHANGELOG.md, example/lib/shared/enemy/goblin.dart, lib/base/bonfire_game.dart, lib/camera/bonfire_camera.dart, lib/collision/collision_config.dart, lib/collision/object_collision.dart, lib/map/base/tile.dart, lib/map/base/tile_with_collision.dart, lib/map/world_map.dart, lib/util/extensions/enemy/rotation_enemy_extensions.dart, lib/util/extensions/game_component_extensions.dart, lib/util/extensions/player/rotation_player_extensions.dart, lib/widgets/mini_map/mini_map.dart, lib/widgets/mini_map/mini_map_canvas.dart, pubspec.yaml
- Do correction suggested by issue [#327](https://github.com/RafaelBarbosatec/bonfire/issues/327). Thanks [Fixid-Fuzz](https://github.com/Fixid-Fuzz)!
- Camera improvements.
- remove required `animation` in `simpleAttackMeleeByAngle`.
=> Version 2.10.9

CHANGELOG.md, example/lib/shared/enemy/goblin.dart, example/pubspec.lock, lib/base/listener_game_widget.dart, lib/game_interface/game_interface.dart, lib/widgets/mini_map/mini_map_canvas.dart, pubspec.lock, pubspec.yaml
- Update Flame to `1.4.0`.
- Improvements in `MiniMap`: Adds `zoom` param. [#325](https://github.com/RafaelBarbosatec/bonfire/issues/325)
=> Version 2.10.10

CHANGELOG.md, example/lib/simple_example/simple_example_game.dart, lib/base/base_game.dart, lib/base/bonfire_game.dart, lib/base/bonfire_game_interface.dart, lib/joystick/joystick.dart, lib/joystick/joystick_controller.dart, lib/mixins/keyboard_listener.dart, lib/mixins/move_to_position_along_the_path.dart, lib/tiled/builder/tiled_world_builder.dart, pubspec.yaml
- Adds methods `enableGestures` and `enableKeyboard` in `gameRef`(BonfireGameInterface)
- Adds mixin `KeyboardEventListener`.
- Fix exception in `TiledWorldBuilder`.
=> Version 2.11.3

CHANGELOG.md, lib/tiled/builder/tiled_world_builder.dart, pubspec.yaml
- Fix exception in `TiledWorldBuilder`.
=> Version 2.11.4

CHANGELOG.md, example/pubspec.lock, lib/base/game_component.dart, lib/base/listener_game_widget.dart, pubspec.lock, pubspec.yaml
=> Version 2.11.6

CHANGELOG.md, example/lib/shared/npc/critter/critter.dart, lib/mixins/move_to_position_along_the_path.dart, lib/mixins/movement.dart, lib/mixins/movement_by_joystick.dart
Enemies used to move faster on diagonal movement, now their movement was normalized.
This PR also organizes better how this is handled and updates NPC speed in the example to better follow the player speed. 
=> Fix diagonal movement speed for enemies

CHANGELOG.md, lib/camera/bonfire_camera.dart, pubspec.yaml
- Fix bug in `moveOnlyMapArea`
=> Version 2.11.8

CHANGELOG.md, example/pubspec.lock, lib/base/bonfire_game.dart, lib/map/base/tile.dart, lib/map/base/tile_model.dart, lib/map/world_map.dart, lib/mixins/movement.dart, lib/mixins/use_sprite_animation.dart, lib/tiled/builder/tiled_world_builder.dart, lib/tiled/model/tiled_object_properties.dart, lib/util/direction_animations/simple_direction_animation.dart, lib/util/interval_tick.dart, lib/util/value_generator_component.dart, pubspec.yaml
- Consider Tiled layer opacity. Fix [#356](https://github.com/RafaelBarbosatec/bonfire/issues/356)
- Little improvements performance.
- Adds param `area` in `TiledObjectProperties`.
- - Fix multi instance of `AnimatedObjectOnce` in `SimpleDirectionAnimation`. [#359](https://github.com/RafaelBarbosatec/bonfire/issues/359)
=> Version 2.11.10

CHANGELOG.md, example/assets/images/tiled/mapa2.json, lib/camera/bonfire_camera.dart, lib/util/value_generator_component.dart, pubspec.yaml
- Fix [#261](https://github.com/RafaelBarbosatec/bonfire/issues/261)
- Fix [#364](https://github.com/RafaelBarbosatec/bonfire/issues/364)
=> Version 2.11.11

example/pubspec.lock, lib/base/base_game.dart, lib/base/listener_game_widget.dart, lib/util/extensions/extensions.dart, lib/util/follower_widget.dart, pubspec.lock, pubspec.yaml
=> Version 2.12.1

lib/objects/follower_object.dart
This PR adds a simple FollowerObject which works like the AnimatedFollowerObject but uses a sprite instead of an animation
=> FollowerObject with simple Sprite

CHANGELOG.md, lib/objects/follower_object.dart, pubspec.yaml
- Adds `FollowerObject`. Thanks [Matt El Mouktafi](https://github.com/mel-mouk)!
=> Version 2.12.2

CHANGELOG.md, lib/collision/object_collision.dart, lib/joystick/joystick.dart, lib/mixins/movement_by_joystick.dart, lib/mixins/pushable.dart, lib/objects/flying_attack_object.dart, pubspec.yaml
- Fix issue [#379](https://github.com/RafaelBarbosatec/bonfire/issues/379)
- Adds in `ObjectCollision` the method `onCollisionHappened`
=> Version 2.12.3

.github/workflows/unit.yml, CHANGELOG.md, example/lib/shared/npc/critter/critter.dart, lib/mixins/attackable.dart, lib/objects/flying_attack_object.dart, pubspec.yaml
- Fix issue [#402](https://github.com/RafaelBarbosatec/bonfire/issues/402)
=> Version 2.12.4

CHANGELOG.md, example/lib/shared/interface/knight_interface.dart, lib/mixins/direction_animation.dart, lib/mixins/paint_transformer.dart, lib/util/direction_animations/simple_direction_animation.dart, pubspec.yaml
- Adds `playOnceOther` in `SimpleDirectionAnimation`
- Now the flip operation did by `SimpleDirectionAnimation` not flip the component.
=> Version 2.12.5

.github/workflows/unit.yml, CHANGELOG.md, example/pubspec.lock, lib/base/bonfire_game.dart, lib/widgets/mini_map/mini_map.dart, pubspec.lock, pubspec.yaml
- Adds fixed Flame version to `1.7.3`
- Update Flutter sdk range `<4.0.0`
- Fix issue [413](https://github.com/RafaelBarbosatec/bonfire/issues/413)
=> Version 2.12.6

.github/workflows/unit.yml, CHANGELOG.md, pubspec.yaml
- Fix issue [417](https://github.com/RafaelBarbosatec/bonfire/issues/417). Thanks [Matt El Mouktafi](https://github.com/mel-mouk)
=> Version 2.12.7

CHANGELOG.md, lib/joystick/joystick.dart, lib/joystick/joystick_directional.dart
FYI:
Update joystick.dart #433
and also added for joystick
=> Option for using to enable diagonal input events.

CHANGELOG.md, example/lib/shared/player/knight.dart
fix for this
https://github.com/RafaelBarbosatec/bonfire/issues/432
=> Fix [Bug]: The goblin attacks while in conversation #432

.github/workflows/unit.yml, CHANGELOG.md, example/lib/core/app_routes.dart, example/lib/pages/enemy/enemy_route.dart, example/lib/pages/input/keyboard/barrel_show_keyboard_input.dart, example/lib/pages/lighting/lighting_route.dart, example/lib/pages/path_finding/path_finding_route.dart, example/lib/pages/player/platform/platform_player_route.dart, example/lib/pages/player/simple/simple_player_route.dart, example/lib/shared/decoration/barrel_dragable.dart, example/pubspec.lock, lib/forces/handle_forces.dart, lib/joystick/joystick_controller.dart, lib/lighting/lighting_component.dart, lib/mixins/movement.dart, pubspec.lock, pubspec.yaml
- Update Flame to `1.10.0`.
- `Movement` improvements.
-  Fix bug when use `Movement` mixin and the `MoveEffect`.
=> Version 3.0.1

CHANGELOG.md, example/assets/images/platform/simple_map_gem.tmj, example/assets/images/tiled/punnyworld/punyworld_tileset.tsj, example/assets/images/tiled/punnyworld/simple_map.tmj, example/lib/pages/enemy/melee_enemy.dart, example/lib/pages/player/simple/simple_player_page.dart, example/pubspec.lock, lib/base/bonfire_game.dart, lib/base/game_component.dart, lib/camera/bonfire_camera.dart, lib/camera/camera_config.dart, lib/camera/camera_effects.dart, lib/map/base/map_game.dart, lib/map/base/tile.dart, lib/mixins/bouncing_object.dart, lib/mixins/movement.dart, lib/tiled/builder/tiled_world_builder.dart, pubspec.lock, pubspec.yaml
- Now all Tile in the map have you own Paint.
- Update `tiledjsonreader` to `1.3.3`.
- Tiled improvements : Now if you set the class of objectlayer to `collision`, all object of this layer will be collision.
- Adds param `resolution` in `CameraConfig`.
=> Version 3.0.3

CHANGELOG.md, example/lib/pages/map/tiled/tiled_page.dart, lib/map/base/tile.dart, lib/util/controlled_update_animation.dart, pubspec.yaml
- Fix blending pixel bug in tile with animation.
=> Version 3.0.4

CHANGELOG.md, example/lib/pages/forces/forces_page.dart, example/lib/shared/player/player_dialog.dart, lib/base/bonfire_game.dart, lib/behavior/behavior.dart, lib/behavior/behavior_manager.dart, lib/behavior/behaviors/b_contition/b_condition.dart, lib/behavior/behaviors/b_contition/condition.dart, lib/behavior/behaviors/b_contition/conditions/c_can_see.dart, lib/behavior/behaviors/b_contition/conditions/c_can_see_type.dart, lib/behavior/behaviors/b_contition/conditions/c_custom.dart, lib/behavior/behaviors/b_custom.dart, lib/behavior/behaviors/b_move_to_component.dart, lib/bonfire.dart, lib/scene_builder/actions/camera_scene_action.dart, lib/scene_builder/actions/move_scene_action.dart, lib/util/component_spawner.dart, lib/util/direction_animations/simple_direction_animation.dart, pubspec.yaml
- Fix bug unwanted push when component have BlockMovementCollision.
=> Version 3.0.8

CHANGELOG.md, example/lib/shared/decoration/barrel_dragable.dart, lib/camera/camera_config.dart, lib/mixins/path_finding.dart, lib/mixins/pushable.dart, lib/util/line_path_component.dart, pubspec.yaml
- adds new Pushable configurations. (`pushableFrom`,`pushPerCellEnabled`,`cellSize`,`pushPerCellDuration`,`pushPerCellCurve`)
- adds method `List<Vector2> getPathToPosition` in mixin `PathFinding`
=> Version 3.0.9

.github/workflows/unit.yml, CHANGELOG.md, example/.metadata, example/lib/pages/mini_games/top_down_game/robot_enemy.dart, example/pubspec.lock, lib/base/listener_game_widget.dart, lib/mixins/movement.dart, lib/tiled/reader/tiled_network_reader.dart, lib/tiled/reader/tiled_reader.dart, lib/widgets/typewriter/typewriter.dart, pubspec.lock, pubspec.yaml
- Adds `header` param in `TiledNetworkReader`
- Update Flame to `1.15.0`
=> Version 3.4.0

CHANGELOG.md, example/.gitignore, example/lib/pages/path_finding/human_path_finding.dart, lib/input/gestures/drag_gesture.dart, lib/mixins/path_finding.dart, lib/mixins/vision.dart, lib/tiled/builder/tiled_world_builder.dart, lib/tiled/reader/tiled_asset_reader.dart, pubspec.yaml
- Adds `moveAlongThePath` method in `PathFinding` mixin.
- Bugfix in `Vision` mixin.
=> Version 3.6.1

CHANGELOG.md, example/pubspec.lock, lib/camera/bonfire_camera.dart, lib/util/extensions/extensions.dart, pubspec.lock, pubspec.yaml
=> Version 3.7.0

CHANGELOG.md, example/lib/pages/mini_games/manual_map/game_manual_map.dart, lib/input/player_controller.dart, lib/map/spritefusion/builder/spritefusion_world_builder.dart, lib/map/spritefusion/world_map_by_spritefusion.dart, lib/map/tiled/builder/tiled_world_builder.dart, lib/map/tiled/model/tiled_world_data.dart, lib/mixins/attackable.dart, lib/objects/flying_attack_game_object.dart, lib/player/platform_player.dart, pubspec.yaml
- Fix bug in the `PlatformPlayer` movements.
- Adds `objectsBuilder` in `WorldMapBySpritefusion`. You can select a layer to adds objects in the tile position.
=> Version 3.8.3

CHANGELOG.md, lib/mixins/interval_checker.dart, lib/mixins/jumper_animation.dart, lib/npc/enemy/platform_enemy.dart, pubspec.yaml
- Fix bug in `JumperAnimation`
=> Version 3.8.5

CHANGELOG.md, example/lib/pages/mini_games/simple_example/my_enemy.dart, example/lib/pages/mini_games/top_down_game/robot_enemy.dart, example/lib/shared/enemy/goblin.dart, example/lib/shared/npc/critter/critter.dart, lib/collision/block_movement_collision.dart, lib/mixins/automatic_random_movement.dart, lib/mixins/movement.dart, lib/mixins/path_finding.dart, pubspec.yaml
- Fix bug collision. [#511](https://github.com/RafaelBarbosatec/bonfire/issues/511)
- Renamed `AutomaticRandomMovement` to `RandomMovement`
- `RandomMovement` improvements! Now works in `PLatformEnemy`
=> Version 3.8.6

CHANGELOG.md, example/.metadata, example/lib/pages/player/simple/human.dart, example/pubspec.lock, lib/bonfire.dart, lib/camera/bonfire_camera.dart, lib/collision/block_movement_collision.dart, lib/input/gestures/drag_gesture.dart, lib/input/gestures/move_camera_using_gestures.dart, lib/input/gestures/pinch_gesture.dart, lib/input/gestures/tap_gesture.dart, lib/input/input.dart, lib/input/mouse_listener.dart, lib/mixins/bouncing_object.dart, lib/mixins/pointer_detector.dart, lib/mixins/update_camera_by_pinch_gesture.dart, pubspec.yaml
- `BlockMovementCollision` improvements.
- Create a `PinchGesture` mixin to listen pinch gestures.
- Create a `UpdateCameraByPinchGesture` mixin to update zoom and camera position in pinch events.
=> Version 3.9.1

CHANGELOG.md, lib/util/direction_animations/simple_direction_animation.dart
1. It makes `isFlipHorizontallyFastAnimation` and `isFlipVerticallyFastAnimation` public
2. Assigns values of `isFlipHorizontally` and `isFlipVertically` respectively to `isFlipHorizontallyFastAnimation` and `isFlipVerticallyFastAnimation`
=> Fix for #523

CHANGELOG.md, example/lib/pages/mini_games/lpc/lpc_player.dart, example/lib/shared/interface/knight_interface.dart, lib/util/extensions/game_component_extensions.dart, lib/util/follower_widget.dart, pubspec.yaml
- Fix bug in `FollowerWidget`.
- Fix bug in `SimpleDirectionAnimation` where fast animation direction did not change when character direction changed. Thanks [tkshnwesper](https://github.com/tkshnwesper)
=> Version 3.9.4

CHANGELOG.md, lib/base/bonfire_game.dart, lib/base/bonfire_game_interface.dart, lib/input/gestures/drag_gesture.dart, lib/input/gestures/gesture_event.dart, lib/input/gestures/pinch_gesture.dart, lib/input/gestures/tap_gesture.dart, lib/input/keyboard/keyboard.dart, lib/input/player_controller.dart, lib/joystick/joystick.dart, lib/joystick/joystick_action.dart, lib/joystick/joystick_directional.dart, lib/lighting/lighting_component.dart, lib/npc/enemy/platform_enemy.dart, lib/player/platform_player.dart, lib/util/direction_animations/platform_animations.dart, lib/util/extensions/game_component_extensions.dart, lib/util/extensions/viewport_extension.dart, lib/util/follower_widget.dart, pubspec.yaml
- Fix Joystick bug when viewport is fixed resolution. [#526](https://github.com/RafaelBarbosatec/bonfire/issues/526)
=> Version 3.9.5

CHANGELOG.md, example/lib/shared/interface/knight_interface.dart, example/pubspec.lock, lib/mixins/attackable.dart, lib/scene_builder/actions/await_scene_action.dart, lib/scene_builder/actions/callback_scene_action.dart, lib/scene_builder/actions/move_to_position_scene_action.dart, lib/scene_builder/actions/move_while_scene_action.dart, lib/scene_builder/actions/wait_scene_action.dart, lib/scene_builder/scene_builder.dart, pubspec.yaml
- BREAKING CHANGE: Bump Flutter SDK minimum version to 3.22.0
- Upgrade: Packages (flame v1.18.0, http v1.2.2, a_star_algorithm v0.3.2).
- Adds new SceneActions
=> Version 3.10.0

CHANGELOG.md, example/pubspec.lock, example/web/index.html, lib/base/bonfire_game.dart, lib/base/bonfire_game_interface.dart, lib/base/game_component.dart, lib/collision/block_movement_collision.dart, lib/map/world_map.dart, lib/mixins/movement.dart, pubspec.lock, pubspec.yaml
=> Version 3.10.1

CHANGELOG.md, example/devtools_options.yaml, lib/base/base_game.dart, lib/base/listener_game_widget.dart, pubspec.yaml
- Clean up componentes when game will removed. `onRemove`.
=> Version 3.10.3

CHANGELOG.md, example/pubspec.lock, lib/base/game_component.dart, lib/mixins/path_finding.dart, pubspec.lock, pubspec.yaml
- Adds param `withDiagonal` in `setupPathFinding` (PathFinding mixin)
- Fix PathFinding bug. Now not consider your own collision as a barrier.
=> Version 3.10.5

.github/workflows/publish.yml, CHANGELOG.md, example/lib/pages/home/home_page.dart, example/lib/pages/player/simple/human.dart, example/lib/pages/shader/shader_config_controller.dart, example/lib/pages/shader/shader_config_panel.dart, example/lib/pages/shader/shader_layer_configuration.dart, example/lib/pages/shader/shader_page.dart, example/pubspec.lock, example/pubspec.yaml, example/shaders/baseShader.frag, example/shaders/waterShaderV2.frag, lib/base/bonfire_game.dart, lib/base/game_component.dart, lib/bonfire.dart, lib/mixins/random_movement.dart, lib/mixins/shader/shader_setter.dart, lib/mixins/shader/shader_util.dart, lib/mixins/shader/use_shader.dart, pubspec.lock, pubspec.yaml
- Resolve the alignment and visibility issues when using the MiniMap widget with non-1.0 zoom values. Thanks [qulvmp6](https://github.com/qulvmp6)
- Adds `randomMovementArea` param in `RandomMovement` mixin.
=> Version 3.12.1

CHANGELOG.md, example/ios/Podfile, example/lib/pages/mini_games/random_map/map_generator.dart, example/pubspec.lock, lib/base/base_game.dart, lib/collision/quad_tree/custom_collision_detection.dart, lib/collision/quad_tree/custom_has_quadtree_collision_detection.dart, lib/collision/quad_tree/custom_quad_tree_broadphase.dart, lib/mixins/shader/shader_setter.dart, lib/util/extensions/color_extensions.dart, pubspec.lock, pubspec.yaml
=> Version 3.12.6

CHANGELOG.md, lib/mixins/shader/shader_setter.dart, pubspec.lock, pubspec.yaml
- rollback to deprecated RGB colors
=> Version 3.13.3

CHANGELOG.md, README.md, example/pubspec.lock, lib/mixins/use_barlife.dart, lib/util/barlife_component.dart, pubspec.lock, pubspec.yaml
=> Version 3.13.4

CHANGELOG.md, README.md, lib/util/barlife_component.dart, pubspec.lock, pubspec.yaml
- Fix ellipse and polygon collision objects in Tiled maps, the `CollisionType` was set to `inactive`, changed to `active` as the `RectangleHitbox`.
- Fiz padding in `BarLifeComponent`
=> Version 3.13.5
